<!-- Generate page. Menus on left, middle and possible right box -->
<table border=0 cellspacing=0 cellpadding=2 width=100% class=boxes>
<tr><td class=boxes-spacer width=5>&nbsp;</td><td valign=top class=boxes>
<!-- Static menus -->

<table border=0 cellspacing=1 cellpadding=0 class=menus-outer><tr><td>
  <table cellspacing=0 cellpadding=1 width=100%>
    <tr><td valign=center class=menus-top>&nbsp;Main</td></tr>
    <tr><td class=menus>
      &nbsp;<a class=menus href="http://csg.sph.umich.edu">CSG Home</a>

    </td></tr>
  </table>
</td></tr></table><br>

