
<!-- End static menus -->
</td>
<td class=boxes-spacer>&nbsp;</td>
<td valign=top class=boxes width=100%>
<!-- Start page of real HTML/PHP -->
<table border=0 cellspacing=1 cellpadding=0 class=midbox-outer width=100%>
<tr><td width=100%>
<table cellspacing=0 cellpadding=1 class=midbox width=100%>
<tr><td class=midbox-spacer>&nbsp;</td><td class=midbox width=100%><br>
<!-- Rest of HTML goes after this -->
